model:
  base_learning_rate: 1.0e-05
  target: ar123.models.nvs.model.MVDiffusion
  params:
    drop_cond_prob: 0.1

    stable_diffusion_config:
      pretrained_model_name_or_path: sudo-ai/zero123plus-v1.2
      custom_pipeline: ./ar123/models/nvs

    use_checkpoint: false
    fine_tune: false

data:
  target: ar123.data.dataset_pl.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    train:
      target: ar123.data.dataset.Zero123plusData
      params:
        root_dir: "./zero123plus_renders" ## the path of the zero123plus_renders dataset
        meta_fname: ""
        validation: false
    validation:
      target: ar123.data.dataset.Zero123plusData
      params:
        root_dir: "./zero123plus_renders" ## the path of the zero123plus_renders dataset
        meta_fname: ""
        validation: true


lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 5000
      save_top_k: -1
      save_last: true
  callbacks: {}

  trainer:
    benchmark: true
    max_epochs: -1
    gradient_clip_val: 1.0
    val_check_interval: 5000
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    check_val_every_n_epoch: null   # if not set this, validation does not run
